from _model import Paises


def migrate_paises(db):
    db.session.add(Paises("008", "Abu Dhabi"))
    db.session.add(Paises("009", "Dirce"))
    db.session.add(Paises("013", "Afeganistao"))
    db.session.add(Paises("017", "Albania, Republica Da"))
    db.session.add(Paises("020", "Alboran-Perejil,Ilhas"))
    db.session.add(Paises("023", "Alemanha"))
    db.session.add(Paises("025", "Alemanha, Republica Democratica"))
    db.session.add(Paises("031", "Burkina Faso"))
    db.session.add(Paises("037", "Andorra"))
    db.session.add(Paises("040", "Angola"))
    db.session.add(Paises("041", "Anguilla"))
    db.session.add(Paises("043", "Antigua E Barbuda"))
    db.session.add(Paises("047", "Antilhas Holandesas"))
    db.session.add(Paises("053", "Arabia Saudita"))
    db.session.add(Paises("059", "Argelia"))
    db.session.add(Paises("063", "Argentina"))
    db.session.add(Paises("064", "Armenia, Republica Da"))
    db.session.add(Paises("065", "Aruba"))
    db.session.add(Paises("069", "Australia"))
    db.session.add(Paises("072", "Austria"))
    db.session.add(Paises("073", "Azerbaijao, Republica Do"))
    db.session.add(Paises("077", "Bahamas, Ilhas"))
    db.session.add(Paises("080", "Bahrein, Ilhas"))
    db.session.add(Paises("081", "Bangladesh"))
    db.session.add(Paises("083", "Barbados"))
    db.session.add(Paises("085", "Belarus, Republica Da"))
    db.session.add(Paises("087", "Belgica"))
    db.session.add(Paises("088", "Belize"))
    db.session.add(Paises("090", "Bermudas"))
    db.session.add(Paises("093", "Mianmar (BIRMANIA)"))
    db.session.add(Paises("097", "Bolivia, Estado Plurinacional Da"))
    db.session.add(Paises("098", "Bosnia-Herzegovina (REPUBLICA Da)"))
    db.session.add(Paises("100", "Int.Z.F.Manaus"))
    db.session.add(Paises("101", "Botsuana"))
    db.session.add(Paises("105", "Brasil"))
    db.session.add(Paises("106", "Fretado P/Brasil"))
    db.session.add(Paises("108", "Brunei"))
    db.session.add(Paises("111", "Bulgaria, Republica Da"))
    db.session.add(Paises("115", "Burundi"))
    db.session.add(Paises("119", "Butao"))
    db.session.add(Paises("127", "Cabo Verde, Republica De"))
    db.session.add(Paises("131", "Cachemira"))
    db.session.add(Paises("137", "Cayman, Ilhas"))
    db.session.add(Paises("141", "Camboja"))
    db.session.add(Paises("145", "Camaroes"))
    db.session.add(Paises("149", "Canada"))
    db.session.add(Paises("150", "Jersey, Ilha Do Canal"))
    db.session.add(Paises("151", "Canarias, Ilhas"))
    db.session.add(Paises("152", "Canal,Ilhas"))
    db.session.add(Paises("153", "Cazaquistao, Republica Do"))
    db.session.add(Paises("154", "Catar"))
    db.session.add(Paises("158", "Chile"))
    db.session.add(Paises("160", "China, Republica Popular"))
    db.session.add(Paises("161", "Formosa (TAIWAN)"))
    db.session.add(Paises("163", "Chipre"))
    db.session.add(Paises("165", "Cocos(Keeling),Ilhas"))
    db.session.add(Paises("169", "Colombia"))
    db.session.add(Paises("173", "Comores, Ilhas"))
    db.session.add(Paises("177", "Congo"))
    db.session.add(Paises("183", "Cook, Ilhas"))
    db.session.add(Paises("187", "Coreia (DO Norte), Rep.Pop.Democratica"))
    db.session.add(Paises("190", "Coreia (DO Sul), Republica Da"))
    db.session.add(Paises("193", "Costa Do Marfim"))
    db.session.add(Paises("195", "Croacia (REPUBLICA Da)"))
    db.session.add(Paises("196", "Costa Rica"))
    db.session.add(Paises("198", "Coveite"))
    db.session.add(Paises("199", "Cuba"))
    db.session.add(Paises("229", "Benin"))
    db.session.add(Paises("232", "Dinamarca"))
    db.session.add(Paises("235", "Dominica,Ilha"))
    db.session.add(Paises("237", "Dubai"))
    db.session.add(Paises("239", "Equador"))
    db.session.add(Paises("240", "Egito"))
    db.session.add(Paises("243", "Eritreia"))
    db.session.add(Paises("244", "Emirados Arabes Unidos"))
    db.session.add(Paises("245", "Espanha"))
    db.session.add(Paises("246", "Eslovenia, Republica Da"))
    db.session.add(Paises("247", "Eslovaca, Republica"))
    db.session.add(Paises("249", "Estados Unidos"))
    db.session.add(Paises("251", "Estonia, Republica Da"))
    db.session.add(Paises("253", "Etiopia"))
    db.session.add(Paises("255", "Falkland (ILHAS Malvinas)"))
    db.session.add(Paises("259", "Feroe, Ilhas"))
    db.session.add(Paises("263", "Fezzan"))
    db.session.add(Paises("267", "Filipinas"))
    db.session.add(Paises("271", "Finlandia"))
    db.session.add(Paises("275", "Franca"))
    db.session.add(Paises("281", "Gabao"))
    db.session.add(Paises("285", "Gambia"))
    db.session.add(Paises("289", "Gana"))
    db.session.add(Paises("291", "Georgia, Republica Da"))
    db.session.add(Paises("293", "Gibraltar"))
    db.session.add(Paises("297", "Granada"))
    db.session.add(Paises("301", "Grecia"))
    db.session.add(Paises("305", "Groenlandia"))
    db.session.add(Paises("309", "Guadalupe"))
    db.session.add(Paises("313", "Guam"))
    db.session.add(Paises("317", "Guatemala"))
    db.session.add(Paises("325", "Guiana Francesa"))
    db.session.add(Paises("329", "Guine"))
    db.session.add(Paises("331", "Guine-Equatorial"))
    db.session.add(Paises("334", "Guine-Bissau"))
    db.session.add(Paises("337", "Guiana"))
    db.session.add(Paises("341", "Haiti"))
    db.session.add(Paises("345", "Honduras"))
    db.session.add(Paises("351", "Hong Kong"))
    db.session.add(Paises("355", "Hungria, Republica Da"))
    db.session.add(Paises("357", "Iemen"))
    db.session.add(Paises("358", "Iemem Do Sul"))
    db.session.add(Paises("359", "Man, Ilha De"))
    db.session.add(Paises("361", "India"))
    db.session.add(Paises("365", "Indonesia"))
    db.session.add(Paises("367", "Inglaterra"))
    db.session.add(Paises("369", "Iraque"))
    db.session.add(Paises("372", "Ira, Republica Islamica Do"))
    db.session.add(Paises("375", "Irlanda"))
    db.session.add(Paises("379", "Islandia"))
    db.session.add(Paises("383", "Israel"))
    db.session.add(Paises("386", "Italia"))
    db.session.add(Paises("388", "Servia E Montenegro"))
    db.session.add(Paises("391", "Jamaica"))
    db.session.add(Paises("395", "Jammu"))
    db.session.add(Paises("396", "Johnston, Ilhas"))
    db.session.add(Paises("399", "Japao"))
    db.session.add(Paises("403", "Jordania"))
    db.session.add(Paises("411", "Kiribati"))
    db.session.add(Paises("420", "Laos, Rep.Pop.Democr.Do"))
    db.session.add(Paises("423", "Lebuan,Ilhas"))
    db.session.add(Paises("426", "Lesoto"))
    db.session.add(Paises("427", "Letonia, Republica Da"))
    db.session.add(Paises("431", "Libano"))
    db.session.add(Paises("434", "Liberia"))
    db.session.add(Paises("438", "Libia"))
    db.session.add(Paises("440", "Liechtenstein"))
    db.session.add(Paises("442", "Lituania, Republica Da"))
    db.session.add(Paises("445", "Luxemburgo"))
    db.session.add(Paises("447", "Macau"))
    db.session.add(Paises("449", "Macedonia, Ant.Rep.Iugoslava"))
    db.session.add(Paises("450", "Madagascar"))
    db.session.add(Paises("452", "Ilha Da Madeira"))
    db.session.add(Paises("455", "Malasia"))
    db.session.add(Paises("458", "Malavi"))
    db.session.add(Paises("461", "Maldivas"))
    db.session.add(Paises("464", "Mali"))
    db.session.add(Paises("467", "Malta"))
    db.session.add(Paises("472", "Marianas Do Norte"))
    db.session.add(Paises("474", "Marrocos"))
    db.session.add(Paises("476", "Marshall,Ilhas"))
    db.session.add(Paises("477", "Martinica"))
    db.session.add(Paises("485", "Mauricio"))
    db.session.add(Paises("488", "Mauritania"))
    db.session.add(Paises("490", "Midway, Ilhas"))
    db.session.add(Paises("493", "Mexico"))
    db.session.add(Paises("494", "Moldavia, Republica Da"))
    db.session.add(Paises("495", "Monaco"))
    db.session.add(Paises("497", "Mongolia"))
    db.session.add(Paises("499", "Micronesia"))
    db.session.add(Paises("501", "Montserrat,Ilhas"))
    db.session.add(Paises("505", "Mocambique"))
    db.session.add(Paises("507", "Namibia"))
    db.session.add(Paises("508", "Nauru"))
    db.session.add(Paises("511", "Christmas,Ilha (NAVIDAD)"))
    db.session.add(Paises("517", "Nepal"))
    db.session.add(Paises("521", "Nicaragua"))
    db.session.add(Paises("525", "Niger"))
    db.session.add(Paises("528", "Nigeria"))
    db.session.add(Paises("531", "Niue,Ilha"))
    db.session.add(Paises("535", "Norfolk,Ilha"))
    db.session.add(Paises("538", "Noruega"))
    db.session.add(Paises("542", "Nova Caledonia"))
    db.session.add(Paises("545", "Papua Nova Guine"))
    db.session.add(Paises("548", "Nova Zelandia"))
    db.session.add(Paises("551", "Vanuatu"))
    db.session.add(Paises("556", "Oma"))
    db.session.add(Paises("563", "Pacifico,Ilhas Do (ADMINISTRACAO Dos Eua)"))
    db.session.add(Paises("566", "Pacifico,Ilhas Do (POSSESSAO Dos Eua)"))
    db.session.add(Paises("569", "Pacifico,Ilhas Do (TERRITORIO Em Fideicomisso Dos"))
    db.session.add(Paises("573", "Paises Baixos (HOLANDA)"))
    db.session.add(Paises("575", "Palau"))
    db.session.add(Paises("576", "Paquistao"))
    db.session.add(Paises("578", "Palestina"))
    db.session.add(Paises("580", "Panama"))
    db.session.add(Paises("583", "Papua Nova GuinÈ"))
    db.session.add(Paises("586", "Paraguai"))
    db.session.add(Paises("589", "Peru"))
    db.session.add(Paises("593", "Pitcairn,Ilha"))
    db.session.add(Paises("599", "Polinesia Francesa"))
    db.session.add(Paises("603", "Polonia, Republica Da"))
    db.session.add(Paises("607", "Portugal"))
    db.session.add(Paises("611", "Porto Rico"))
    db.session.add(Paises("623", "Quenia"))
    db.session.add(Paises("625", "Quirguiz, Republica"))
    db.session.add(Paises("628", "Reino Unido"))
    db.session.add(Paises("640", "Republica Centro-Africana"))
    db.session.add(Paises("647", "Republica Dominicana"))
    db.session.add(Paises("660", "Reuniao, Ilha"))
    db.session.add(Paises("665", "Zimbabue"))
    db.session.add(Paises("670", "Romenia"))
    db.session.add(Paises("675", "Ruanda"))
    db.session.add(Paises("676", "Russia, Federacao Da"))
    db.session.add(Paises("677", "Salomao, Ilhas"))
    db.session.add(Paises("678", "Saint Kitts E Nevis"))
    db.session.add(Paises("685", "Saara Ocidental"))
    db.session.add(Paises("687", "El Salvador"))
    db.session.add(Paises("690", "Samoa"))
    db.session.add(Paises("691", "Samoa Americana"))
    db.session.add(Paises("695", "Sao Cristovao E Neves,Ilhas"))
    db.session.add(Paises("697", "San Marino"))
    db.session.add(Paises("700", "Sao Pedro E Miquelon"))
    db.session.add(Paises("705", "Sao Vicente E Granadinas"))
    db.session.add(Paises("710", "Santa Helena"))
    db.session.add(Paises("715", "Santa Lucia"))
    db.session.add(Paises("720", "Sao Tome E Principe, Ilhas"))
    db.session.add(Paises("728", "Senegal"))
    db.session.add(Paises("731", "Seychelles"))
    db.session.add(Paises("735", "Serra Leoa"))
    db.session.add(Paises("738", "Sikkim"))
    db.session.add(Paises("741", "Cingapura"))
    db.session.add(Paises("744", "Siria, Republica Arabe Da"))
    db.session.add(Paises("748", "Somalia"))
    db.session.add(Paises("750", "Sri Lanka"))
    db.session.add(Paises("754", "Suazilandia"))
    db.session.add(Paises("756", "Africa Do Sul"))
    db.session.add(Paises("759", "Sudao"))
    db.session.add(Paises("764", "Suecia"))
    db.session.add(Paises("767", "Suica"))
    db.session.add(Paises("770", "Suriname"))
    db.session.add(Paises("772", "Tadjiquistao, Republica Do"))
    db.session.add(Paises("776", "Tailandia"))
    db.session.add(Paises("780", "Tanzania, Rep.Unida Da"))
    db.session.add(Paises("782", "Territorio Brit.Oc.Indico"))
    db.session.add(Paises("783", "Djibuti"))
    db.session.add(Paises("785", "Territorio da Alta Comissao do Pacifico Ocidental"))
    db.session.add(Paises("788", "Chade"))
    db.session.add(Paises("790", "Tchecoslovaquia"))
    db.session.add(Paises("791", "Tcheca, Republica"))
    db.session.add(Paises("795", "Timor Leste"))
    db.session.add(Paises("800", "Togo"))
    db.session.add(Paises("805", "Toquelau,Ilhas"))
    db.session.add(Paises("810", "Tonga"))
    db.session.add(Paises("815", "Trinidad E Tobago"))
    db.session.add(Paises("820", "Tunisia"))
    db.session.add(Paises("823", "Turcas E Caicos,Ilhas"))
    db.session.add(Paises("824", "Turcomenistao, Republica Do"))
    db.session.add(Paises("827", "Turquia"))
    db.session.add(Paises("828", "Tuvalu"))
    db.session.add(Paises("831", "Ucrania"))
    db.session.add(Paises("833", "Uganda"))
    db.session.add(Paises("840", "Uniao Das Republicas Socialistas Sovieticas"))
    db.session.add(Paises("845", "Uruguai"))
    db.session.add(Paises("847", "Uzbequistao, Republica Do"))
    db.session.add(Paises("848", "Vaticano, Est.Da Cidade Do"))
    db.session.add(Paises("850", "Venezuela"))
    db.session.add(Paises("855", "Vietname Norte"))
    db.session.add(Paises("858", "Vietna"))
    db.session.add(Paises("863", "Virgens,Ilhas (BRITANICAS)"))
    db.session.add(Paises("866", "Virgens,Ilhas (E.U.A.)"))
    db.session.add(Paises("870", "Fiji"))
    db.session.add(Paises("873", "Wake, Ilha"))
    db.session.add(Paises("875", "Wallis E Futuna, Ilhas"))
    db.session.add(Paises("888", "Congo, Republica Democratica Do"))
    db.session.commit()
