
insert into paises values ('008', 'Abu Dhabi');
insert into paises values ('009', 'Dirce');
insert into paises values ('013', 'Afeganistao');
insert into paises values ('017', 'Albania, Republica Da');
insert into paises values ('020', 'Alboran-Perejil,Ilhas');
insert into paises values ('023', 'Alemanha');
insert into paises values ('025', 'Alemanha, Republica Democratica');
insert into paises values ('031', 'Burkina Faso');
insert into paises values ('037', 'Andorra');
insert into paises values ('040', 'Angola');
insert into paises values ('041', 'Anguilla');
insert into paises values ('043', 'Antigua E Barbuda');
insert into paises values ('047', 'Antilhas Holandesas');
insert into paises values ('053', 'Arabia Saudita');
insert into paises values ('059', 'Argelia');
insert into paises values ('063', 'Argentina');
insert into paises values ('064', 'Armenia, Republica Da');
insert into paises values ('065', 'Aruba');
insert into paises values ('069', 'Australia');
insert into paises values ('072', 'Austria');
insert into paises values ('073', 'Azerbaijao, Republica Do');
insert into paises values ('077', 'Bahamas, Ilhas');
insert into paises values ('080', 'Bahrein, Ilhas');
insert into paises values ('081', 'Bangladesh');
insert into paises values ('083', 'Barbados');
insert into paises values ('085', 'Belarus, Republica Da');
insert into paises values ('087', 'Belgica');
insert into paises values ('088', 'Belize');
insert into paises values ('090', 'Bermudas');
insert into paises values ('093', 'Mianmar (BIRMANIA)');
insert into paises values ('097', 'Bolivia, Estado Plurinacional Da');
insert into paises values ('098', 'Bosnia-Herzegovina (REPUBLICA Da)');
insert into paises values ('100', 'Int.Z.F.Manaus');
insert into paises values ('101', 'Botsuana');
insert into paises values ('105', 'Brasil');
insert into paises values ('106', 'Fretado P/Brasil');
insert into paises values ('108', 'Brunei');
insert into paises values ('111', 'Bulgaria, Republica Da');
insert into paises values ('115', 'Burundi');
insert into paises values ('119', 'Butao');
insert into paises values ('127', 'Cabo Verde, Republica De');
insert into paises values ('131', 'Cachemira');
insert into paises values ('137', 'Cayman, Ilhas');
insert into paises values ('141', 'Camboja');
insert into paises values ('145', 'Camaroes');
insert into paises values ('149', 'Canada');
insert into paises values ('150', 'Jersey, Ilha Do Canal');
insert into paises values ('151', 'Canarias, Ilhas');
insert into paises values ('152', 'Canal,Ilhas');
insert into paises values ('153', 'Cazaquistao, Republica Do');
insert into paises values ('154', 'Catar');
insert into paises values ('158', 'Chile');
insert into paises values ('160', 'China, Republica Popular');
insert into paises values ('161', 'Formosa (TAIWAN)');
insert into paises values ('163', 'Chipre');
insert into paises values ('165', 'Cocos(Keeling),Ilhas');
insert into paises values ('169', 'Colombia');
insert into paises values ('173', 'Comores, Ilhas');
insert into paises values ('177', 'Congo');
insert into paises values ('183', 'Cook, Ilhas');
insert into paises values ('187', 'Coreia (DO Norte), Rep.Pop.Democratica');
insert into paises values ('190', 'Coreia (DO Sul), Republica Da');
insert into paises values ('193', 'Costa Do Marfim');
insert into paises values ('195', 'Croacia (REPUBLICA Da)');
insert into paises values ('196', 'Costa Rica');
insert into paises values ('198', 'Coveite');
insert into paises values ('199', 'Cuba');
insert into paises values ('229', 'Benin');
insert into paises values ('232', 'Dinamarca');
insert into paises values ('235', 'Dominica,Ilha');
insert into paises values ('237', 'Dubai');
insert into paises values ('239', 'Equador');
insert into paises values ('240', 'Egito');
insert into paises values ('243', 'Eritreia');
insert into paises values ('244', 'Emirados Arabes Unidos');
insert into paises values ('245', 'Espanha');
insert into paises values ('246', 'Eslovenia, Republica Da');
insert into paises values ('247', 'Eslovaca, Republica');
insert into paises values ('249', 'Estados Unidos');
insert into paises values ('251', 'Estonia, Republica Da');
insert into paises values ('253', 'Etiopia');
insert into paises values ('255', 'Falkland (ILHAS Malvinas)');
insert into paises values ('259', 'Feroe, Ilhas');
insert into paises values ('263', 'Fezzan');
insert into paises values ('267', 'Filipinas');
insert into paises values ('271', 'Finlandia');
insert into paises values ('275', 'Franca');
insert into paises values ('281', 'Gabao');
insert into paises values ('285', 'Gambia');
insert into paises values ('289', 'Gana');
insert into paises values ('291', 'Georgia, Republica Da');
insert into paises values ('293', 'Gibraltar');
insert into paises values ('297', 'Granada');
insert into paises values ('301', 'Grecia');
insert into paises values ('305', 'Groenlandia');
insert into paises values ('309', 'Guadalupe');
insert into paises values ('313', 'Guam');
insert into paises values ('317', 'Guatemala');
insert into paises values ('325', 'Guiana Francesa');
insert into paises values ('329', 'Guine');
insert into paises values ('331', 'Guine-Equatorial');
insert into paises values ('334', 'Guine-Bissau');
insert into paises values ('337', 'Guiana');
insert into paises values ('341', 'Haiti');
insert into paises values ('345', 'Honduras');
insert into paises values ('351', 'Hong Kong');
insert into paises values ('355', 'Hungria, Republica Da');
insert into paises values ('357', 'Iemen');
insert into paises values ('358', 'Iemem Do Sul');
insert into paises values ('359', 'Man, Ilha De');
insert into paises values ('361', 'India');
insert into paises values ('365', 'Indonesia');
insert into paises values ('367', 'Inglaterra');
insert into paises values ('369', 'Iraque');
insert into paises values ('372', 'Ira, Republica Islamica Do');
insert into paises values ('375', 'Irlanda');
insert into paises values ('379', 'Islandia');
insert into paises values ('383', 'Israel');
insert into paises values ('386', 'Italia');
insert into paises values ('388', 'Servia E Montenegro');
insert into paises values ('391', 'Jamaica');
insert into paises values ('395', 'Jammu');
insert into paises values ('396', 'Johnston, Ilhas');
insert into paises values ('399', 'Japao');
insert into paises values ('403', 'Jordania');
insert into paises values ('411', 'Kiribati');
insert into paises values ('420', 'Laos, Rep.Pop.Democr.Do');
insert into paises values ('423', 'Lebuan,Ilhas');
insert into paises values ('426', 'Lesoto');
insert into paises values ('427', 'Letonia, Republica Da');
insert into paises values ('431', 'Libano');
insert into paises values ('434', 'Liberia');
insert into paises values ('438', 'Libia');
insert into paises values ('440', 'Liechtenstein');
insert into paises values ('442', 'Lituania, Republica Da');
insert into paises values ('445', 'Luxemburgo');
insert into paises values ('447', 'Macau');
insert into paises values ('449', 'Macedonia, Ant.Rep.Iugoslava');
insert into paises values ('450', 'Madagascar');
insert into paises values ('452', 'Ilha Da Madeira');
insert into paises values ('455', 'Malasia');
insert into paises values ('458', 'Malavi');
insert into paises values ('461', 'Maldivas');
insert into paises values ('464', 'Mali');
insert into paises values ('467', 'Malta');
insert into paises values ('472', 'Marianas Do Norte');
insert into paises values ('474', 'Marrocos');
insert into paises values ('476', 'Marshall,Ilhas');
insert into paises values ('477', 'Martinica');
insert into paises values ('485', 'Mauricio');
insert into paises values ('488', 'Mauritania');
insert into paises values ('490', 'Midway, Ilhas');
insert into paises values ('493', 'Mexico');
insert into paises values ('494', 'Moldavia, Republica Da');
insert into paises values ('495', 'Monaco');
insert into paises values ('497', 'Mongolia');
insert into paises values ('499', 'Micronesia');
insert into paises values ('501', 'Montserrat,Ilhas');
insert into paises values ('505', 'Mocambique');
insert into paises values ('507', 'Namibia');
insert into paises values ('508', 'Nauru');
insert into paises values ('511', 'Christmas,Ilha (NAVIDAD)');
insert into paises values ('517', 'Nepal');
insert into paises values ('521', 'Nicaragua');
insert into paises values ('525', 'Niger');
insert into paises values ('528', 'Nigeria');
insert into paises values ('531', 'Niue,Ilha');
insert into paises values ('535', 'Norfolk,Ilha');
insert into paises values ('538', 'Noruega');
insert into paises values ('542', 'Nova Caledonia');
insert into paises values ('545', 'Papua Nova Guine');
insert into paises values ('548', 'Nova Zelandia');
insert into paises values ('551', 'Vanuatu');
insert into paises values ('556', 'Oma');
insert into paises values ('563', 'Pacifico,Ilhas Do (ADMINISTRACAO Dos Eua)');
insert into paises values ('566', 'Pacifico,Ilhas Do (POSSESSAO Dos Eua)');
insert into paises values ('569', 'Pacifico,Ilhas Do (TERRITORIO Em Fideicomisso Dos');
insert into paises values ('573', 'Paises Baixos (HOLANDA)');
insert into paises values ('575', 'Palau');
insert into paises values ('576', 'Paquistao');
insert into paises values ('578', 'Palestina');
insert into paises values ('580', 'Panama');
insert into paises values ('583', 'Papua Nova Guiné');
insert into paises values ('586', 'Paraguai');
insert into paises values ('589', 'Peru');
insert into paises values ('593', 'Pitcairn,Ilha');
insert into paises values ('599', 'Polinesia Francesa');
insert into paises values ('603', 'Polonia, Republica Da');
insert into paises values ('607', 'Portugal');
insert into paises values ('611', 'Porto Rico');
insert into paises values ('623', 'Quenia');
insert into paises values ('625', 'Quirguiz, Republica');
insert into paises values ('628', 'Reino Unido');
insert into paises values ('640', 'Republica Centro-Africana');
insert into paises values ('647', 'Republica Dominicana');
insert into paises values ('660', 'Reuniao, Ilha');
insert into paises values ('665', 'Zimbabue');
insert into paises values ('670', 'Romenia');
insert into paises values ('675', 'Ruanda');
insert into paises values ('676', 'Russia, Federacao Da');
insert into paises values ('677', 'Salomao, Ilhas');
insert into paises values ('678', 'Saint Kitts E Nevis');
insert into paises values ('685', 'Saara Ocidental');
insert into paises values ('687', 'El Salvador');
insert into paises values ('690', 'Samoa');
insert into paises values ('691', 'Samoa Americana');
insert into paises values ('695', 'Sao Cristovao E Neves,Ilhas');
insert into paises values ('697', 'San Marino');
insert into paises values ('700', 'Sao Pedro E Miquelon');
insert into paises values ('705', 'Sao Vicente E Granadinas');
insert into paises values ('710', 'Santa Helena');
insert into paises values ('715', 'Santa Lucia');
insert into paises values ('720', 'Sao Tome E Principe, Ilhas');
insert into paises values ('728', 'Senegal');
insert into paises values ('731', 'Seychelles');
insert into paises values ('735', 'Serra Leoa');
insert into paises values ('738', 'Sikkim');
insert into paises values ('741', 'Cingapura');
insert into paises values ('744', 'Siria, Republica Arabe Da');
insert into paises values ('748', 'Somalia');
insert into paises values ('750', 'Sri Lanka');
insert into paises values ('754', 'Suazilandia');
insert into paises values ('756', 'Africa Do Sul');
insert into paises values ('759', 'Sudao');
insert into paises values ('764', 'Suecia');
insert into paises values ('767', 'Suica');
insert into paises values ('770', 'Suriname');
insert into paises values ('772', 'Tadjiquistao, Republica Do');
insert into paises values ('776', 'Tailandia');
insert into paises values ('780', 'Tanzania, Rep.Unida Da');
insert into paises values ('782', 'Territorio Brit.Oc.Indico');
insert into paises values ('783', 'Djibuti');
insert into paises values ('785', 'Territorio da Alta Comissao do Pacifico Ocidental');
insert into paises values ('788', 'Chade');
insert into paises values ('790', 'Tchecoslovaquia');
insert into paises values ('791', 'Tcheca, Republica');
insert into paises values ('795', 'Timor Leste');
insert into paises values ('800', 'Togo');
insert into paises values ('805', 'Toquelau,Ilhas');
insert into paises values ('810', 'Tonga');
insert into paises values ('815', 'Trinidad E Tobago');
insert into paises values ('820', 'Tunisia');
insert into paises values ('823', 'Turcas E Caicos,Ilhas');
insert into paises values ('824', 'Turcomenistao, Republica Do');
insert into paises values ('827', 'Turquia');
insert into paises values ('828', 'Tuvalu');
insert into paises values ('831', 'Ucrania');
insert into paises values ('833', 'Uganda');
insert into paises values ('840', 'Uniao Das Republicas Socialistas Sovieticas');
insert into paises values ('845', 'Uruguai');
insert into paises values ('847', 'Uzbequistao, Republica Do');
insert into paises values ('848', 'Vaticano, Est.Da Cidade Do');
insert into paises values ('850', 'Venezuela');
insert into paises values ('855', 'Vietname Norte');
insert into paises values ('858', 'Vietna');
insert into paises values ('863', 'Virgens,Ilhas (BRITANICAS)');
insert into paises values ('866', 'Virgens,Ilhas (E.U.A.)');
insert into paises values ('870', 'Fiji');
insert into paises values ('873', 'Wake, Ilha');
insert into paises values ('875', 'Wallis E Futuna, Ilhas');
insert into paises values ('888', 'Congo, Republica Democratica Do');
